### PR TITLE
Apply model data filter before instantiating submodels.

### PR DESCRIPTION
**Pull request by myrlund**
Ran into trouble renaming keys for a submodel using a filter. This seems to fix the issue.

### CODE REVIEW

**Comment by tonyhb** [comment]
Thanks for the heads up!  Checking it out now

**Comment by tonyhb** [comment]
@myrlund Would you be able to provide an example here so I can chuck it in a test?

**Comment by myrlund** [comment]
Sure thing! I'm basically running `humps.camelizeKeys` as a filter, which I'm guessing screws with the `Record` objects in some way. Haven't dug too deep, though.

```javascript
import { camelizeKeys } from 'humps';

class BaseModel extends Model {
    static filter = camelizeKeys;
}
```

And this seems to break submodels. Let me know if you need more details!

**Comment by tonyhb** [comment]
Got it!  Going to release 2.0.1 in about 15 minutes once I've made a test for regressions.  Thanks for the heads up!

**Comment by tonyhb** [comment]
@myrlund :+1: released, thanks again!

**Comment by tonyhb** [comment]
Note for issue #56, tests in e923d9489d0fad400344f99bb020d1bf98983fb5

**Pull request merged**
